### ISSUE TITLE
test webserver online

### ISSUE THREAD

**Issue by bgruening** [bgruening/galaxy-rna-workbench#28]
Play with it at: http://192.52.2.98

**Comment by bagnacan** [comment]
I'm testing all tours at the provided IP, and I found two issues in the last one (the exercise tour) :

- step 5's tour bubble overlays the tool's section, which forces the user to click "next" on the tour bubble in order to use the tool column, and then click again "back" to follow all instructions for the tool listed in the tour bubble. Is it possible to do something on the positioning of the tour bubbles?

- step 8's tour bubble asks the user to download "Homo_sapiens_CXCL2_constraints.fa" from zenodo, but the link at the zenodo page lets you download only "Homo_sapiens_CXCL2_sequence.fa", which was used at the previous step

- step 8's tour bubble points the user to download the required file on zenodo (although the name differs, see previous point), but then, differently from to the previous file upload, the tour does not trigger the opening of the upload file dialog. Is that intended?

**Comment by jfallmann** [comment]
@bgruening @bagnacan Thanks for testing, this errors are in no way intended, I had a problem with the zenodo files, seems I published too fast and forgot to add some files, will put them on a temporary public space and correct links for now, zenodo is unreachable atm due to xmas, once this issue is resolved I'll set the correct links and fix the upload dialog

**Comment by jfallmann** [comment]
@bgruening @bagnacan Everything should work now for both tours, happy testing, 
So far everything I tested looked just fine (I mean besides the tours) 
However I never saw the welcome page, it always shows "To customize this page you can create a welcome.html page in your directory mounted to /export."

**Comment by bgruening** [comment]
@jfallmann please make sure to always make `docker pull` before you start your container again to get the latest version. If you pull tomorrow morning, you will get your latest tour fixes as well.
Also clear your browser cache, this can also be a reason.

**Comment by jfallmann** [comment]
@bgruening Done and surprise, it worked ;) Thx for the tip!

**Comment by bgruening** [comment]
Sure thing! Guten Rutsch!

**Comment by jfallmann** [comment]
Danke gleichfalls!

**Comment by bagnacan** [comment]
Hi all, and happy new year!
Sorry I could not help you more before the deadline, I was unable to get a properly working connection back at my parents'.

@jfallmann I'm redoing the viennarna exercise tour, but the automatic upload at step 8 seems to fail:
at the bubble "We will now upload the file containing constraints (the file 'Homo_sapiens_CXCL2_constraints.fa') from github to Galaxy. In contrast to the beginning of this tour, this will be done automatically this time" I click "Next". Here, the Galaxy upload window appears, but the status field for the upload of the aforementioned file says "Failed: Upload content incomplete".
I tried to complete the task by uploading the file manually and parametrizing RNAFold according to what's written in the tour, but when I hit "Execute", Galaxy complains with the message "Fatal error: Exit code 1 () ERROR: structure constraint is too long" in the history

The new welcome page is really nice! kudos!

**Comment by bagnacan** [comment]
Some very minor wording issues in the ViennaRNA tour:

- very first bubble: "Read and Follow" --> "Read and follow"
- step 8, while providing instructions on how to parametrize RNAfold, entry #6 says 'The constraints are in the input fasta file', but in the Galaxy interface "input fasta" and "fasta input" are swapped, so entry #6 should align to that with 'The constraints are in the fasta input file'

**Comment by bgruening** [comment]
@bagnacan please create a PR :)

**Comment by jfallmann** [comment]
@bagnacan @bgruening 
Hi and happy new year to you too, No idea why this fails, worked fine for me, also the constraint to long error is somewhat weird, will check this out tomorrow, thanks for doublechecking!

**Comment by jfallmann** [comment]
@bagnacan @bgruening I fixed these issues and worked a bit on the textbox settings so they don't overlay the input area when using tools, should work now, PR incoming

**Comment by bgruening** [comment]
Please test all again!

**Comment by s-will** [comment]
Hi @bgruening, is the server down? Maybe the current docker image does not work, I cannot locally run it (conncetion to the postgres database refused). I see the same error "This site can't be reached" when trying to connect to this server or  to a local instance.

**Comment by jfallmann** [comment]
@bgruening Can't run my local workbench after latest docker pull, results in 403 forbidden error, also the test server seems to be down, any ideas why?

**Comment by bgruening** [comment]
Hi have you updated Docker recently? What does `docker info` tell you? Can you please check to not use the `overlay` storage backend and rather try to use the devicemapper? See here: https://docs.docker.com/engine/userguide/storagedriver/selectadriver/

**Comment by jfallmann** [comment]
Seems it was a docker update related problem, docker 1.12.6 with overlay works fine, 1.13.1 not, will switch from overlay as suggested, thanks for the hint

**Comment by bgruening** [comment]
Can you try this one: bit.ly/RNAworkbench
This is also the address written in the letter to the editor.

**Comment by jfallmann** [comment]
@bgruening Testserver works fine for me
